CREATE DATABASE IF NOT EXISTS disaster_db;
USE disaster_db;

CREATE TABLE incidents (
  id INT AUTO_INCREMENT PRIMARY KEY,
  type VARCHAR(50) NOT NULL,
  severity ENUM('LOW','MEDIUM','HIGH','CRITICAL') NOT NULL,
  location VARCHAR(200) NOT NULL,
  latitude DECIMAL(9,6) DEFAULT 0,
  longitude DECIMAL(9,6) DEFAULT 0,
  description TEXT,
  reported_by VARCHAR(100),
  contact_number VARCHAR(20),
  dead_count INT DEFAULT 0,
  injured_count INT DEFAULT 0,
  missing_count INT DEFAULT 0,
  displaced_count INT DEFAULT 0,
  status ENUM('ACTIVE','INVESTIGATING','RESOLVED','CLOSED') DEFAULT 'ACTIVE',
  reported_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE resources (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  type ENUM('RESCUE_TEAM','VEHICLE','MEDICAL','SHELTER','FOOD','EQUIPMENT') NOT NULL,
  quantity INT DEFAULT 1,
  location VARCHAR(200),
  status ENUM('AVAILABLE','DEPLOYED','MAINTENANCE') DEFAULT 'AVAILABLE',
  incident_id INT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (incident_id) REFERENCES incidents(id) ON DELETE SET NULL
);

CREATE TABLE alerts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(200) NOT NULL,
  level ENUM('INFO','WARNING','DANGER','EVACUATION') NOT NULL,
  region VARCHAR(150),
  message TEXT NOT NULL,
  status ENUM('ACTIVE','RESOLVED') DEFAULT 'ACTIVE',
  incident_id INT NULL,
  sent_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  expires_at TIMESTAMP NULL,
  FOREIGN KEY (incident_id) REFERENCES incidents(id) ON DELETE SET NULL
);